[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Redirect rules for form submissions  
[[redirects]]
  from = "/partner-success"
  to = "/partner/success"
  status = 200

# Catch-all redirect for SPA behavior (but preserve existing files)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["visitor"], Country = ["!"]} 